"""Baseline samplers for the gradient-guided ablation study.

These three samplers exist primarily as comparison targets for
:class:`STLGradientGuidedSampler`:

* :class:`StandardSampler`. vanilla LLM sampling. The ``lambda = 0``
  ablation. Single sample, no verifier feedback.
* :class:`BestOfNSampler`. standard Best-of-N with binary STL
  acceptance: among ``N`` rollouts, return the first with ``rho > 0``,
  falling back to the first sample if none satisfies. Models the
  "filter-then-train" recipe inherited from SERA.
* :class:`ContinuousBoNSampler`. BoN with continuous ``rho`` scoring:
  among ``N`` rollouts, return the argmax-rho sample. The strongest
  no-gradient baseline; the question gradient guidance must beat is "is
  having ``grad rho`` worth more than just generating more samples?".

All three implement the :class:`Sampler` protocol from
:mod:`stl_seed.inference.protocol`.

"""

from __future__ import annotations

from typing import Any

import jax
import jax.numpy as jnp
import jaxtyping as jt

from stl_seed.inference.protocol import LLMProposal, SamplerDiagnostics, SamplerResult
from stl_seed.specs import Node, STLSpec
from stl_seed.stl.evaluator import compile_spec
from stl_seed.tasks._trajectory import Trajectory

# ---------------------------------------------------------------------------
# Internal helper: roll out one trajectory under an LLM proposal.
# ---------------------------------------------------------------------------


def _rollout(
    llm: LLMProposal,
    simulator: Any,
    sim_params: Any,
    aux: dict[str, Any] | None,
    vocabulary: jt.Float[jt.Array, "K m"],
    horizon: int,
    initial_state: jt.Float[jt.Array, " n"],
    key: jt.PRNGKeyArray,
    sampling_temperature: float,
) -> Trajectory:
    """Generate one trajectory by autoregressive LLM sampling.

    Identical decoding loop used by all three baselines, parameterised
    only by ``sampling_temperature``. ``temperature == 0`` collapses to
    greedy argmax decoding; the default ``1.0`` preserves the LLM's
    calibration.
    """
    K, m = int(vocabulary.shape[0]), int(vocabulary.shape[1])
    history = jnp.zeros((0, m), dtype=jnp.float32)
    actions: list[jt.Float[jt.Array, " m"]] = []
    for t in range(horizon):
        step_key = jax.random.fold_in(key, t)
        llm_key, sample_key = jax.random.split(step_key, 2)
        logits = llm(initial_state, history, llm_key)
        logits = jnp.asarray(logits, dtype=jnp.float32)
        if logits.shape != (K,):
            raise ValueError(f"LLM emitted logits of shape {logits.shape}, expected ({K},)")
        if sampling_temperature == 0.0:
            idx = int(jnp.argmax(logits))
        else:
            scaled = logits / sampling_temperature if sampling_temperature != 1.0 else logits
            idx = int(jax.random.categorical(sample_key, scaled))
        a = vocabulary[idx]
        actions.append(a)
        history = jnp.concatenate([history, a[None, :]], axis=0)

    control = jnp.stack(actions, axis=0)
    return _simulate_to_trajectory(simulator, sim_params, aux, initial_state, control, key)


def _simulate_to_trajectory(
    simulator: Any,
    sim_params: Any,
    aux: dict[str, Any] | None,
    initial_state: jt.Float[jt.Array, " n"],
    control: jt.Float[jt.Array, "H m"],
    key: jt.PRNGKeyArray,
) -> Trajectory:
    """Adapter producing a canonical :class:`Trajectory` from any simulator."""
    sim_class_name = type(simulator).__name__
    H, m = int(control.shape[0]), int(control.shape[1])
    if sim_class_name == "GlucoseInsulinSimulator":
        from stl_seed.tasks.glucose_insulin import MealSchedule

        meal_schedule = (
            aux.get("meal_schedule") if aux is not None else None
        ) or MealSchedule.empty()
        states, times, meta = simulator.simulate(
            initial_state, control.reshape(-1), meal_schedule, sim_params, key
        )
        return Trajectory(
            states=states,
            actions=control.reshape(H, m),
            times=times,
            meta=meta,
        )
    return simulator.simulate(initial_state, control, sim_params, key)


# ---------------------------------------------------------------------------
# StandardSampler
# ---------------------------------------------------------------------------


class StandardSampler:
    """Vanilla LLM sampling. no verifier feedback.

    The lambda = 0 ablation. Returns one trajectory generated by greedy
    or temperature-scaled sampling from the LLM's logits, with no
    consultation of the STL spec during generation. The trajectory's
    final ``rho`` is reported in diagnostics for comparison.

    Parameters
    ----------
    llm:
        LLM proposal callable.
    simulator:
        ODE simulator.
    spec:
        STL spec (used only post-hoc for diagnostic reporting).
    action_vocabulary:
        Discrete action set ``V in R^{K x m}``.
    sim_params, horizon, aux:
        Forwarded to the simulator (see
        :class:`STLGradientGuidedSampler` for semantics).
    sampling_temperature:
        Temperature on the LLM softmax. Default 1.0 (calibrated
        sampling); 0.0 for greedy argmax.
    """

    def __init__(
        self,
        llm: LLMProposal,
        simulator: Any,
        spec: STLSpec | Node,
        action_vocabulary: jt.Float[jt.Array, "K m"],
        sim_params: Any,
        *,
        horizon: int,
        aux: dict[str, Any] | None = None,
        sampling_temperature: float = 1.0,
    ) -> None:
        self.llm = llm
        self.simulator = simulator
        self.spec = spec
        self.vocabulary = jnp.asarray(action_vocabulary, dtype=jnp.float32)
        if self.vocabulary.ndim != 2:
            raise ValueError(
                f"action_vocabulary must be 2-d (K, m), got shape {self.vocabulary.shape}"
            )
        self.K, self.m = int(self.vocabulary.shape[0]), int(self.vocabulary.shape[1])
        self.sim_params = sim_params
        self.horizon = int(horizon)
        if self.horizon < 1:
            raise ValueError(f"horizon must be >= 1, got {self.horizon}")
        self.aux = dict(aux) if aux is not None else None
        self.sampling_temperature = float(sampling_temperature)
        self._compiled_spec = compile_spec(spec)

    def sample(
        self,
        initial_state: jt.Float[jt.Array, " n"],
        key: jt.PRNGKeyArray,
    ) -> SamplerResult:
        traj = _rollout(
            self.llm,
            self.simulator,
            self.sim_params,
            self.aux,
            self.vocabulary,
            self.horizon,
            initial_state,
            key,
            self.sampling_temperature,
        )
        rho = float(self._compiled_spec(traj.states, traj.times))
        diag: SamplerDiagnostics = {
            "sampler": "standard",
            "final_rho": rho,
            "n_samples": 1,
            "sampling_temperature": self.sampling_temperature,
        }
        return traj, diag


# ---------------------------------------------------------------------------
# BestOfNSampler
# ---------------------------------------------------------------------------


class BestOfNSampler:
    """Standard Best-of-N: binary STL acceptance, post-hoc filtering.

    Generates ``n`` candidate trajectories, returns the *first* one with
    ``rho > 0`` (binary STL satisfaction). If none satisfies, returns the
    first sample with diagnostic ``found_satisfying = False``.

    This is the "filter then output" baseline matching the SERA pipeline
    convention. It throws away the magnitude of ``rho``.

    Parameters
    ----------
    n:
        Sample budget.
    rho_threshold:
        Binary acceptance threshold. Default 0.0 (Donzé-Maler convention:
        ``rho > 0`` iff trajectory satisfies the spec).

    All other parameters: see :class:`StandardSampler`.
    """

    def __init__(
        self,
        llm: LLMProposal,
        simulator: Any,
        spec: STLSpec | Node,
        action_vocabulary: jt.Float[jt.Array, "K m"],
        sim_params: Any,
        *,
        horizon: int,
        n: int = 8,
        rho_threshold: float = 0.0,
        aux: dict[str, Any] | None = None,
        sampling_temperature: float = 1.0,
    ) -> None:
        if n < 1:
            raise ValueError(f"n must be >= 1, got {n}")
        self.llm = llm
        self.simulator = simulator
        self.spec = spec
        self.vocabulary = jnp.asarray(action_vocabulary, dtype=jnp.float32)
        if self.vocabulary.ndim != 2:
            raise ValueError(
                f"action_vocabulary must be 2-d (K, m), got shape {self.vocabulary.shape}"
            )
        self.K, self.m = int(self.vocabulary.shape[0]), int(self.vocabulary.shape[1])
        self.sim_params = sim_params
        self.horizon = int(horizon)
        if self.horizon < 1:
            raise ValueError(f"horizon must be >= 1, got {self.horizon}")
        self.aux = dict(aux) if aux is not None else None
        self.n = int(n)
        self.rho_threshold = float(rho_threshold)
        self.sampling_temperature = float(sampling_temperature)
        self._compiled_spec = compile_spec(spec)

    def sample(
        self,
        initial_state: jt.Float[jt.Array, " n"],
        key: jt.PRNGKeyArray,
    ) -> SamplerResult:
        all_traj: list[Trajectory] = []
        all_rho: list[float] = []
        chosen: int = 0
        found_satisfying = False
        for i in range(self.n):
            sub_key = jax.random.fold_in(key, i)
            traj = _rollout(
                self.llm,
                self.simulator,
                self.sim_params,
                self.aux,
                self.vocabulary,
                self.horizon,
                initial_state,
                sub_key,
                self.sampling_temperature,
            )
            rho = float(self._compiled_spec(traj.states, traj.times))
            all_traj.append(traj)
            all_rho.append(rho)
            if not found_satisfying and rho > self.rho_threshold:
                chosen = i
                found_satisfying = True
                # Note: we keep generating to fill diagnostics for
                # apples-to-apples compute comparison with the gradient-
                # guided sampler. The chosen trajectory is the *first*
                # acceptable one (canonical BoN early-stop semantics on
                # the *return*, not on the *compute*). If callers want
                # early-stop compute too, set n=1 and call repeatedly.
        diag: SamplerDiagnostics = {
            "sampler": "best_of_n",
            "n_samples": self.n,
            "all_rho": all_rho,
            "chosen_index": chosen,
            "chosen_rho": all_rho[chosen],
            "max_rho": max(all_rho),
            "found_satisfying": found_satisfying,
            "rho_threshold": self.rho_threshold,
            "final_rho": all_rho[chosen],
            "sampling_temperature": self.sampling_temperature,
        }
        return all_traj[chosen], diag


# ---------------------------------------------------------------------------
# ContinuousBoNSampler
# ---------------------------------------------------------------------------


class ContinuousBoNSampler:
    """BoN with continuous ``rho`` scoring: argmax-rho selection.

    Generates ``n`` candidate trajectories and returns the one with the
    highest ``rho``. Unlike :class:`BestOfNSampler`, this uses the full
    real-valued ``rho`` rather than a binary acceptance threshold, so it
    benefits from the same continuous semantics that
    :class:`STLGradientGuidedSampler` exploits. but only post-hoc.

    The hypothesis underlying gradient-guided sampling is that
    *during-sampling* use of the gradient strictly dominates *post-hoc*
    use of the same continuous signal at matched sample budget. This
    sampler is the strict baseline that hypothesis must beat.

    Parameters: same as :class:`BestOfNSampler` (``n`` is the budget;
    no ``rho_threshold``. selection is unconditional argmax).
    """

    def __init__(
        self,
        llm: LLMProposal,
        simulator: Any,
        spec: STLSpec | Node,
        action_vocabulary: jt.Float[jt.Array, "K m"],
        sim_params: Any,
        *,
        horizon: int,
        n: int = 8,
        aux: dict[str, Any] | None = None,
        sampling_temperature: float = 1.0,
    ) -> None:
        if n < 1:
            raise ValueError(f"n must be >= 1, got {n}")
        self.llm = llm
        self.simulator = simulator
        self.spec = spec
        self.vocabulary = jnp.asarray(action_vocabulary, dtype=jnp.float32)
        if self.vocabulary.ndim != 2:
            raise ValueError(
                f"action_vocabulary must be 2-d (K, m), got shape {self.vocabulary.shape}"
            )
        self.K, self.m = int(self.vocabulary.shape[0]), int(self.vocabulary.shape[1])
        self.sim_params = sim_params
        self.horizon = int(horizon)
        if self.horizon < 1:
            raise ValueError(f"horizon must be >= 1, got {self.horizon}")
        self.aux = dict(aux) if aux is not None else None
        self.n = int(n)
        self.sampling_temperature = float(sampling_temperature)
        self._compiled_spec = compile_spec(spec)

    def sample(
        self,
        initial_state: jt.Float[jt.Array, " n"],
        key: jt.PRNGKeyArray,
    ) -> SamplerResult:
        all_traj: list[Trajectory] = []
        all_rho: list[float] = []
        for i in range(self.n):
            sub_key = jax.random.fold_in(key, i)
            traj = _rollout(
                self.llm,
                self.simulator,
                self.sim_params,
                self.aux,
                self.vocabulary,
                self.horizon,
                initial_state,
                sub_key,
                self.sampling_temperature,
            )
            rho = float(self._compiled_spec(traj.states, traj.times))
            all_traj.append(traj)
            all_rho.append(rho)
        chosen = int(jnp.argmax(jnp.asarray(all_rho)))
        diag: SamplerDiagnostics = {
            "sampler": "continuous_bon",
            "n_samples": self.n,
            "all_rho": all_rho,
            "chosen_index": chosen,
            "chosen_rho": all_rho[chosen],
            "max_rho": max(all_rho),
            "min_rho": min(all_rho),
            "final_rho": all_rho[chosen],
            "sampling_temperature": self.sampling_temperature,
        }
        return all_traj[chosen], diag


__all__ = [
    "BestOfNSampler",
    "ContinuousBoNSampler",
    "StandardSampler",
]
