"""On-policy-rollout MC label computation for PAV (Setlur §3.2).

Background
----------
The audit on 2026-04-26 (see ``paper/pav_v2.md``) flagged the original
``compute_per_step_mc_labels`` (kNN-pooled empirical success) as a
deliberate weakening of Setlur, Nagpal, Fisch et al. ("Rewarding Progress:
Scaling Automated Process Verifiers", arXiv:2410.08146). The Setlur paper
estimates per-step MC value via *fresh* on-policy continuations:

    MC(prefix_<= t)  =  E_{tail ~ pi}[ 1{rho(prefix || tail) > 0} ]

This module implements that estimator faithfully against the in-repo
canonical store. Concretely, given a canonical Trajectory whose
``actions`` were produced by the canonical policy:

* For every prefix length t in {0, ..., H},
  - keep ``actions[:t]`` from the canonical trajectory,
  - sample K i.i.d. random tails ``actions[t:H]`` under a uniform-on-box
    random policy (the in-repo ``RandomPolicy`` action support),
  - re-integrate the simulator with the hybrid ``(prefix || tail_k)``
    control sequence,
  - compute ``rho`` against the spec, and report ``mean_k 1{rho > 0}``.
* Compute advantages ``A_t = MC(t+1) - MC(t)`` for ``t = 0, ..., H-1``.

Cost is ``N_traj * (H+1) * K`` ODE integrations vs zero for the kNN
estimator. On the M-series with ``H=12, K=5`` and ``N_traj=2000`` the cost
is in the tens of seconds for glucose-insulin; bio_ode.repressilator is
slower because the ODE integration is heavier per call.

What "on-policy" means here
---------------------------
Setlur et al. roll out under whatever policy the model under evaluation
will use at inference time. We do not have a learned proposer here: the
canonical store was generated by a mix of {random, constant, heuristic}
policies, and the verifier is later applied to *whatever* trajectories
candidate methods produce. We use the *random-uniform-on-action-box*
policy as the on-policy reference distribution: it is the broadest
no-prior baseline and matches the worst-case "uninformed proposer"
assumption under which a process verifier most needs to be discriminative.
This is documented as a caveat in ``paper/pav_v2.md`` and is faithful to
the spirit of Setlur §3.2, which says "the rollout policy is the policy
the verifier is supposed to score".

API
---
The two public entry points are:

* :func:`compute_per_step_mc_labels_onpolicy_glucose_insulin` --- the
  glucose-insulin specialization (the simulator takes a ``meal_schedule``
  in ``aux``).
* :func:`compute_per_step_mc_labels_onpolicy_bio_ode` --- the bio_ode
  family (repressilator / toggle / mapk; the simulator takes only
  ``params``).

Both return :class:`stl_seed.baselines.pav.StepDataset`.

The dispatcher :func:`compute_per_step_mc_labels_onpolicy` picks the right
specialization from the canonical metadata's ``task`` string. If the task
is unsupported we raise ``NotImplementedError`` with a clear message
rather than silently falling back to kNN; the caller is expected to
catch this and explicitly degrade in their reporting.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from typing import Any

import jax
import jax.numpy as jnp
import numpy as np

from stl_seed.baselines.pav import StepDataset, _state_at_step
from stl_seed.specs import REGISTRY, STLSpec
from stl_seed.stl.evaluator import evaluate_robustness
from stl_seed.tasks._trajectory import Trajectory

# ---------------------------------------------------------------------------
# Common helpers.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class OnPolicyRolloutStats:
    """Diagnostics emitted alongside the StepDataset.

    Recording these lets the v2 markdown report tell a reviewer how many
    fresh ODE integrations were charged to PAV, so the wall-clock and
    cost-asymmetry numbers are honest.
    """

    n_trajectories: int
    horizon: int
    K_per_step: int
    n_simulations: int  # = n_trajectories * (horizon + 1) * K
    wall_time_s: float
    spec_key: str


def _draw_random_tail(
    rng: np.random.Generator,
    horizon: int,
    action_dim: int,
    action_low: float,
    action_high: float,
) -> np.ndarray:
    """One i.i.d. uniform-on-box random control sequence of shape (H, m)."""
    return rng.uniform(
        low=action_low,
        high=action_high,
        size=(horizon, action_dim),
    ).astype(np.float32)


def _stl_satisfies(spec: STLSpec, trajectory: Trajectory) -> int:
    """Wrap evaluate_robustness into a {0, 1} satisfaction indicator.

    Inf rho is treated as +/-1e9 (matches the convention in
    :mod:`stl_seed.baselines.comparison`).
    """
    rho = float(evaluate_robustness(spec, trajectory))
    if not np.isfinite(rho):
        return 1 if rho > 0 else 0
    return int(rho > 0.0)


def _build_step_dataset_from_mc(
    canonical_trajectories: list[Trajectory],
    mc: np.ndarray,
    horizon: int,
) -> StepDataset:
    """Convert a per-(traj, step) MC table into the flat StepDataset.

    ``mc`` has shape ``(N_traj, H + 1)`` --- one MC estimate per prefix
    length, with ``mc[:, 0]`` being the unconditioned success probability
    (no actions committed yet) and ``mc[:, H]`` the terminal indicator.
    Advantages are ``mc[:, t+1] - mc[:, t]`` for ``t = 0, ..., H-1``.
    """
    N = len(canonical_trajectories)
    state_dim = int(np.asarray(canonical_trajectories[0].states).shape[1])
    H = int(horizon)
    flat_states = np.zeros((N * H, state_dim), dtype=np.float32)
    flat_traj = np.repeat(np.arange(N, dtype=np.int64), H)
    flat_step = np.tile(np.arange(H, dtype=np.int64), N)
    for i, traj in enumerate(canonical_trajectories):
        for k in range(H):
            flat_states[i * H + k] = _state_at_step(traj, k, H).astype(np.float32)
    flat_adv = (mc[:, 1:] - mc[:, :H]).astype(np.float32).reshape(-1)
    return StepDataset(
        states=flat_states,
        advantages=flat_adv,
        traj_ids=flat_traj,
        step_ids=flat_step,
    )


# ---------------------------------------------------------------------------
# Glucose-insulin specialization.
# ---------------------------------------------------------------------------


def compute_per_step_mc_labels_onpolicy_glucose_insulin(
    canonical_trajectories: list[Trajectory],
    spec: STLSpec,
    *,
    K: int = 5,
    seed: int = 0,
) -> tuple[StepDataset, OnPolicyRolloutStats]:
    """On-policy rollout MC labels for glucose-insulin canonical trajectories.

    For each canonical trajectory ``i`` and prefix length ``t in 0..H``:

        prefix = canonical_trajectories[i].actions[:t]
        for k in 1..K:
            tail_k ~ Uniform([U_INSULIN_MIN, U_INSULIN_MAX]) ** (H - t)
            traj_k = sim(initial_state, prefix || tail_k)
            succ_k = 1{rho(spec, traj_k) > 0}
        mc[i, t] = mean_k succ_k

    The simulator and initial state are reconstructed from the in-repo
    glucose-insulin defaults (``GlucoseInsulinSimulator()``,
    ``BergmanParams()``, empty meal schedule, normal-subject IS) ---
    matching ``scripts/generate_canonical.py``'s wiring exactly.
    """
    # Local import: avoids loading diffrax / glucose-insulin simulator code
    # in environments where the module is imported only for kNN PAV.
    from stl_seed.generation.runner import _simulate_one
    from stl_seed.tasks.glucose_insulin import (
        U_INSULIN_MAX_U_PER_H,
        U_INSULIN_MIN_U_PER_H,
        BergmanParams,
        GlucoseInsulinSimulator,
        MealSchedule,
        default_normal_subject_initial_state,
    )

    if K < 1:
        raise ValueError(f"K must be >= 1, got {K}")
    if not canonical_trajectories:
        raise ValueError("canonical_trajectories must be non-empty")

    sim = GlucoseInsulinSimulator()
    params = BergmanParams()
    initial_state = default_normal_subject_initial_state(params)
    meal_schedule = MealSchedule.empty()
    aux = {"meal_schedule": meal_schedule}

    horizon = int(np.asarray(canonical_trajectories[0].actions).shape[0])
    action_dim = 1
    action_low = float(U_INSULIN_MIN_U_PER_H)
    action_high = float(U_INSULIN_MAX_U_PER_H)

    rng = np.random.default_rng(int(seed))

    # The simulator returns Trajectory pytrees deterministically given a
    # control sequence. We pre-allocate a (N, H+1) MC table.
    N = len(canonical_trajectories)
    mc = np.zeros((N, horizon + 1), dtype=np.float64)
    t_total = time.time()

    # JAX key bookkeeping --- the simulator itself ignores the key (placeholder
    # arg in the protocol) but we still split a per-rollout key for future-
    # proofing if a stochastic noise term ever lands.
    base_key = jax.random.PRNGKey(int(seed))
    key_idx = 0

    for i, traj in enumerate(canonical_trajectories):
        prefix_actions_full = np.asarray(traj.actions, dtype=np.float32)  # (H, 1)
        # Defensive shape check.
        if prefix_actions_full.shape != (horizon, action_dim):
            raise ValueError(
                f"glucose_insulin trajectory {i}: actions shape "
                f"{prefix_actions_full.shape}, expected ({horizon}, {action_dim})"
            )
        for t in range(horizon + 1):
            # Special-case: t == horizon means the prefix is the full
            # canonical action sequence; there's no tail to draw, so
            # mc[i, H] == 1{rho(canonical_traj) > 0} *exactly*.
            if t == horizon:
                mc[i, horizon] = float(_stl_satisfies(spec, traj))
                continue
            successes = 0
            for _ in range(int(K)):
                tail = _draw_random_tail(
                    rng=rng,
                    horizon=horizon - t,
                    action_dim=action_dim,
                    action_low=action_low,
                    action_high=action_high,
                )
                control = np.concatenate([prefix_actions_full[:t], tail], axis=0)
                sim_key = jax.random.fold_in(base_key, key_idx)
                key_idx += 1
                rolled = _simulate_one(
                    simulator=sim,
                    task="glucose_insulin",
                    initial_state=initial_state,
                    control_sequence=control,
                    params=params,
                    aux=aux,
                    key=sim_key,
                )
                successes += _stl_satisfies(spec, rolled)
            mc[i, t] = successes / float(K)

    wall = float(time.time() - t_total)
    ds = _build_step_dataset_from_mc(canonical_trajectories, mc, horizon)
    stats = OnPolicyRolloutStats(
        n_trajectories=int(N),
        horizon=int(horizon),
        K_per_step=int(K),
        n_simulations=int(N * horizon * K),  # t==H is a free pass (no tail)
        wall_time_s=wall,
        spec_key=spec.name,
    )
    return ds, stats


# ---------------------------------------------------------------------------
# Bio-ODE specialization.
# ---------------------------------------------------------------------------


def _bio_ode_simulator_for(task: str) -> tuple[Any, Any, jnp.ndarray, int, int]:
    """Return ``(simulator, params, initial_state, horizon, action_dim)``.

    The wiring matches ``scripts/generate_canonical.py``'s task-family
    factories: same simulator class, same default params, same default
    initial state. If those defaults ever drift out of sync with what the
    canonical store was generated against, on-policy rollouts will produce
    biased MC estimates --- so the v2 driver verifies the simulator
    horizon matches the trajectory's action shape before calling this.
    """
    if task == "bio_ode.repressilator":
        from stl_seed.tasks.bio_ode import (
            RepressilatorSimulator,
            default_repressilator_initial_state,
        )
        from stl_seed.tasks.bio_ode_params import RepressilatorParams

        sim = RepressilatorSimulator()
        params = RepressilatorParams()
        return (
            sim,
            params,
            default_repressilator_initial_state(params),
            int(sim.n_control_points),
            int(sim.action_dim),
        )
    if task == "bio_ode.toggle":
        from stl_seed.tasks.bio_ode import (
            ToggleSimulator,
            default_toggle_initial_state,
        )
        from stl_seed.tasks.bio_ode_params import ToggleParams

        sim = ToggleSimulator()
        params = ToggleParams()
        return (
            sim,
            params,
            default_toggle_initial_state(params),
            int(sim.n_control_points),
            int(sim.action_dim),
        )
    if task == "bio_ode.mapk":
        from stl_seed.tasks.bio_ode import (
            MAPKSimulator,
            default_mapk_initial_state,
        )
        from stl_seed.tasks.bio_ode_params import MAPKParams

        sim = MAPKSimulator()
        params = MAPKParams()
        return (
            sim,
            params,
            default_mapk_initial_state(params),
            int(sim.n_control_points),
            int(sim.action_dim),
        )
    raise NotImplementedError(f"on-policy PAV rollout: bio_ode task {task!r} not wired yet")


def compute_per_step_mc_labels_onpolicy_bio_ode(
    canonical_trajectories: list[Trajectory],
    spec: STLSpec,
    task: str,
    *,
    K: int = 5,
    seed: int = 0,
) -> tuple[StepDataset, OnPolicyRolloutStats]:
    """On-policy rollout MC labels for the bio_ode task families.

    Bio-ode simulators take ``(initial_state, control_sequence, params,
    key)`` and return a Trajectory directly. The action box is [0, 1] for
    repressilator/toggle/mapk per :class:`bio_ode.RepressilatorSimulator`'s
    docstring, which matches the in-repo ``RandomPolicy`` defaults.
    """
    from stl_seed.generation.runner import _simulate_one

    if K < 1:
        raise ValueError(f"K must be >= 1, got {K}")
    if not canonical_trajectories:
        raise ValueError("canonical_trajectories must be non-empty")

    sim, params, initial_state, horizon, action_dim = _bio_ode_simulator_for(task)
    canonical_horizon = int(np.asarray(canonical_trajectories[0].actions).shape[0])
    if canonical_horizon != horizon:
        raise ValueError(
            f"canonical horizon ({canonical_horizon}) != simulator horizon ({horizon}); "
            f"refusing to roll out under a mismatched simulator."
        )
    canonical_action_dim = int(np.asarray(canonical_trajectories[0].actions).shape[1])
    if canonical_action_dim != action_dim:
        raise ValueError(
            f"canonical action_dim ({canonical_action_dim}) != simulator action_dim "
            f"({action_dim}); refusing to roll out under a mismatched simulator."
        )

    rng = np.random.default_rng(int(seed))
    base_key = jax.random.PRNGKey(int(seed))
    key_idx = 0

    N = len(canonical_trajectories)
    mc = np.zeros((N, horizon + 1), dtype=np.float64)
    t_total = time.time()

    action_low = 0.0
    action_high = 1.0

    for i, traj in enumerate(canonical_trajectories):
        prefix_actions_full = np.asarray(traj.actions, dtype=np.float32)
        for t in range(horizon + 1):
            if t == horizon:
                mc[i, horizon] = float(_stl_satisfies(spec, traj))
                continue
            successes = 0
            for _ in range(int(K)):
                tail = _draw_random_tail(
                    rng=rng,
                    horizon=horizon - t,
                    action_dim=action_dim,
                    action_low=action_low,
                    action_high=action_high,
                )
                control = np.concatenate([prefix_actions_full[:t], tail], axis=0)
                sim_key = jax.random.fold_in(base_key, key_idx)
                key_idx += 1
                rolled = _simulate_one(
                    simulator=sim,
                    task=task,
                    initial_state=initial_state,
                    control_sequence=control,
                    params=params,
                    aux=None,
                    key=sim_key,
                )
                successes += _stl_satisfies(spec, rolled)
            mc[i, t] = successes / float(K)

    wall = float(time.time() - t_total)
    ds = _build_step_dataset_from_mc(canonical_trajectories, mc, horizon)
    stats = OnPolicyRolloutStats(
        n_trajectories=int(N),
        horizon=int(horizon),
        K_per_step=int(K),
        n_simulations=int(N * horizon * K),
        wall_time_s=wall,
        spec_key=spec.name,
    )
    return ds, stats


# ---------------------------------------------------------------------------
# Dispatcher.
# ---------------------------------------------------------------------------


def compute_per_step_mc_labels_onpolicy(
    canonical_trajectories: list[Trajectory],
    spec_key: str,
    task: str,
    *,
    K: int = 5,
    seed: int = 0,
) -> tuple[StepDataset, OnPolicyRolloutStats]:
    """Dispatch to the right specialization based on ``task``.

    Raises ``NotImplementedError`` for tasks whose simulator is not
    yet wired; the caller is expected to catch this and explicitly fall
    back to the kNN estimator (or simply skip the cell) in their
    reporting.
    """
    if spec_key not in REGISTRY:
        raise KeyError(f"spec_key {spec_key!r} not in REGISTRY")
    spec = REGISTRY[spec_key]
    if task == "glucose_insulin":
        return compute_per_step_mc_labels_onpolicy_glucose_insulin(
            canonical_trajectories, spec, K=K, seed=seed
        )
    if task.startswith("bio_ode."):
        return compute_per_step_mc_labels_onpolicy_bio_ode(
            canonical_trajectories, spec, task, K=K, seed=seed
        )
    raise NotImplementedError(f"on-policy PAV rollout for task {task!r} is not implemented")


__all__ = [
    "OnPolicyRolloutStats",
    "compute_per_step_mc_labels_onpolicy",
    "compute_per_step_mc_labels_onpolicy_bio_ode",
    "compute_per_step_mc_labels_onpolicy_glucose_insulin",
]
